# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# python-3.10_deej-ai
# 

# Use a Debian-based Python 3.10 image suitable for aarch64
FROM python:3.10-slim-bullseye

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
# - build-essential: for compiling python packages
# - ffmpeg: for audio processing by librosa
# - git: for cloning the repository
RUN apt-get update && apt-get install -y \
    build-essential \
    ffmpeg \
    git \
    && rm -rf /var/lib/apt/lists/*

# Clone the repository into the container
ADD "https://api.github.com/repos/cmarhoover/Deej-AI/commits?per_page=1" latest_commit
COPY Deej-AI .

# Install Python dependencies from the adjusted requirements.txt file
# A separate requirements.txt is used to handle architecture-specific packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on (default for Dash is 8050)
EXPOSE 8050

# The command to run when the container starts
CMD ["python", "Deej-A.I.py", "Pickles", "mp3tovec"]

